version: '3.9'

services:
  server:
    build: "."
    labels:
      - environment=${CURRENT_ENV}
    env_file:
      - .env
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - database
  database:
    image: mongo:6.0.3
    labels:
      - environment=${CURRENT_ENV}
    env_file:
      - .env
    volumes:
      - ./_db-mongo-volume:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
